language: node_js

node_js:
  - "4.2.2"

before_install:
  # Dependencies
  - "curl https://selenium-release.storage.googleapis.com/2.52/selenium-server-standalone-2.52.0.jar > bin/selenium-server-standalone-2.52.0.jar"
  - "curl -s https://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip | funzip > bin/chromedriver && chmod +x bin/chromedriver"
  # X Virtual Framebuffer
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

script: ./runner.sh
